### ISSUE TITLE
Player position

### ISSUE THREAD

**Issue by rivaldo4t** [vaastav/Fantasy-Premier-League#1]
Is there a field corresponding to the position played by the player?

**Comment by vaastav** [comment]
Yup! In players_raw.csv, element_type is the field that corresponds to the position.
1 = GK
2 = DEF
3 = MID
4 = FWD

Maybe I should update the codebase to parse these as well.

**Comment by rivaldo4t** [comment]
Hey, Thanks.
Also, what teams correspond to opponent_teams indices in the data?

**Comment by vaastav** [comment]
IIRC, They are 1-20 with 1 being Arsenal and 20 being West Ham. Note that this depends from season to season.
Its essentially the teams in alphabetical order.

**Comment by rivaldo4t** [comment]
Any way to get it from, for 16-17 and 17-18 both data?
And is there a file describing the fields?

**Comment by vaastav** [comment]
There isn't a file yet. I am waiting for the end of season to run all the parsing again along with any additons.

Don't think I can get 16-17 data from fpl website anymore but you can assume that 1-20 are in alphabetical order.

**Comment by rivaldo4t** [comment]
Thanks
