### ISSUE TITLE
File names

### ISSUE THREAD

**Issue by PrateekJayaPrakash** [vaastav/Fantasy-Premier-League#11]
Hi,

I think it would be better if the player file names were just their IDs instead of name_ID.
It will make it easy to call from MATLAB etc.

Thanks,
Prateek

**Comment by vaastav** [comment]
I considered that but the player IDs change season to season so it could be more annoying to get the data across multiple seasons. Thus, I decided that name_ID is a better option as not only is it unique but it also contains semantic information about the contents
