### ISSUE TITLE
2019/20 api change?

### ISSUE THREAD

**Issue by wamburu** [vaastav/Fantasy-Premier-League#12]
Seems the previous api endpoints are not working with the new season. Getting 404 error and the lib seems to be broken.

**Comment by jeski** [comment]
indeed the api has changed.   for instance, ~drf/bootstrap-static is now ~api/bootstrap-static.
leagues have also changed.  Seems it's been simplified.

**Comment by gringorichards** [comment]
Has anyone figured out a mapping of before/after?
I can see the basic drf -> api change
But what about the other changes? Eg leagues?

**Comment by vaastav** [comment]
Indeed the api has changed. I was away from my computer since FPL came live so I will update the library API in the next couple of days and add some initial data. 
(Expect an update in the next day or 2)

I will take a look around to find all the API links as well.

**Comment by vaastav** [comment]
This is the link for the Arsenal public league : 

https://fantasy.premierleague.com/api/leagues-classic/1/standings/

**Comment by vaastav** [comment]
The library has now been updated to use the new FPL API!

**Comment by jeski** [comment]
cheers mate!

**Comment by wamburu** [comment]
Thanks.

**Comment by RLWH** [comment]
It seems that some of the stats, for example, big_chances_created, big_chances_missed, etc have been missing in the latest API too...

**Comment by vaastav** [comment]
Yea not sure where those stats live. My suspicion is that FPL may have removed them just like with old data (prior to 2013/14)

**Comment by velkokamenov** [comment]
Yes, it is very sad that all those detailed stats are now gone. Is there any chance that they would become available or with the current version of the API that's the best that can be scrapped?

**Comment by vaastav** [comment]
If they become available, I will scrape them  but doesnt seem like FPL is providing them at all.
