### ISSUE TITLE
GW37 csv

### ISSUE THREAD

**Issue by ZeNoonan** [vaastav/Fantasy-Premier-League#124]
Any chance of getting the GW37 csv file into the GWS folder?  Awesome resource and I ask as I want the GW37 data before picking final team of the season for FPL :-)

**Comment by vaastav** [comment]
Sorry, just saw this. Hopefully you had a great end to the season :)

**Comment by vaastav** [comment]
Looks like the file is missing and was never pushed after the update. That is super weird. I'll look into this.

**Comment by kalpesh8** [comment]
yes,, looking for same gw37 csv

**Comment by kz4killua** [comment]
Hi! I have added gw37.csv and xP37.csv and created a pull request. Please review and merge. Thanks for the good work!

**Comment by vaastav** [comment]
Thanks @kz4killua :)

**Comment by Fournierp** [comment]
The **merged_gw.csv** file is still missing the GW37 as well.
