### ISSUE TITLE
Missing data from "Clean_merged_seasons.csv"

### ISSUE THREAD

**Issue by jtorsvik** [vaastav/Fantasy-Premier-League#128]
The datafile "clean_merged_seasons.csv" is missing the second half of the 2021-22 season gameweek data (GW 15-38).

**Comment by vimrajesh** [comment]
I have added it as a PR #127 . Yet to be merged.

**Comment by pedro-vr** [comment]
Hi! Will this PR be merged soon? Does anyone know?

Thanks in advance!

**Comment by vaastav** [comment]
Has been merged now.
