### ISSUE TITLE
New players

### ISSUE THREAD

**Issue by Spyros26** [vaastav/Fantasy-Premier-League#134]
When will the new players to the premier league be added to the 2022-23 season (fpl ids and understat ids)?
Regarding their understat profiles will they be added to the 2021-22understat folder or the 2022-23 understat folder?
Thanks

**Comment by vaastav** [comment]
I will do another update next weekend. Understat data will probably appear after GW1 and will be in the 2022-23 folder.

**Comment by Spyros26** [comment]
I meant the understat IDs for the new players to the Premier league that
already have one of course.
I will be waiting for your next update!
