### ISSUE TITLE
Issues with merged_gw/cleaned_merged_seasons + general gw data

### ISSUE THREAD

**Issue by javaidb** [vaastav/Fantasy-Premier-League#138]
Came across the error when sourcing data for James Maddison, and found only 36/38 gws for 2021-22 season. Parsing through gw data for 2021-22 seasons found he wasn't in merged_gw/cleaned_merged_seasons data for GWs 17,18,21 or 37, while GWs 33 and 36 were doubled up for him. Though it might be a lack of minutes but some of the GWs present he also had no minutes in. Individual GW csv data then showed that he wasn't in GW 18's data, while GWs 33 and 37 were doubled up for him again. The differences in data aren't consistent either which makes it a bit confusing.

Just wondering where the double up comes from, as well as what the absences mean/how they might have come about? Assuming it's the same for others as this is just one player, can help out if I know where you parsed the source data from, let me know :) This repo's golden btw!

**Comment by vaastav** [comment]
All of the data is from the fpl website. Sadly, the gw-by-gw data for last season has been deleted by fpl.IIRC Leicester did have a couple of DGWs last season. This means that Maddison would have double entries for certain entries but no entries for others. I don't recall when the Leicester doubles happened

**Comment by vaastav** [comment]
Ok looks like Leicester had the following DGWs and BGWs:

BGW17, BGW18, and BGW21
DGW33, DGW36, DGW37

This is why Maddison's .csv file has no rows for 17,18, and 21 and 2 rows each for 33,36, and 37.

IN the merged_gw/cleaned_merged_seasons data, Maddison shouldn't have data for GWs17,18, and 21 but should have data (2 rows each) for GW37. Looks like the merged_gw/cleaned_merged_gw files didn't have any GW37 data but this has now been added.
