### ISSUE TITLE
Updates to 2019-20 data after transfer deadline

### ISSUE THREAD

**Issue by djcarter85** [vaastav/Fantasy-Premier-League#14]
Any chance you could update the information in this repo once the transfer deadline has occurred today at 5pm BST? The data is currently a couple of weeks out of date.

Is it just a case of running some python scripts?

**Comment by vaastav** [comment]
Yea I will update it as soon as the deadline ends. And another update tomorrow before GW1 so that FPL has had the chance of adding all the new players

**Comment by djcarter85** [comment]
Thanks so much!

This is a great resource; thanks for providing it.

**Comment by vaastav** [comment]
I have updated it. All the players should be there now.
Cheers! I am glad you find it useful.
