### ISSUE TITLE
404 response from teams_scraper.py

### ISSUE THREAD

**Issue by R70YNS** [vaastav/Fantasy-Premier-League#141]
File "Fantasy-Premier-League/getters.py", line 89, in get_entry_gws_data
    raise Exception("Response was code " + str(response.status_code))
Exception: Response was code 404

Retrieved team id from master_team_list.csv and invoked script using the command:

`python teams_scraper.py 1 22-23 5`

Whereby 1 would be team id for Arsenal during the 2022-2023 season.

**Comment by vaastav** [comment]
teams scraper gets the data for an individual's team and not an epl team.

**Comment by R70YNS** [comment]
Where can individual team ID be retrieved?
