### ISSUE TITLE
gw 12 data not available in data/gw

### ISSUE THREAD

**Issue by sajalgupta23** [vaastav/Fantasy-Premier-League#143]

**Comment by domingodave** [comment]
I just discovered this too, GW12 isn't included in the GW12&13 .csv

**Comment by vaastav** [comment]
Ahh damn. Ok. I will take a look into this today.

**Comment by gracjanstrzelec-digica** [comment]
Now, gw15 data is also missing

**Comment by vaastav** [comment]
GW15 should be there now. GW12 data will be fixed during the WC break.

**Comment by vaastav** [comment]
GW12 data is there now.
