### ISSUE TITLE
GW12 FPL not available

### ISSUE THREAD

**Issue by domingodave** [vaastav/Fantasy-Premier-League#144]
Listed as 'added GW12 + GW13' data, but GW12 is not included in the .csv file. Could you update this please? 👍 :-)

Thanks for the work you've done by the way, top job.

**Comment by vaastav** [comment]
Closing this issue as it is identical to #143 
Will update that issue once I have figured out why the data is missing.

**Comment by domingodave** [comment]
Cheers buddy
