### ISSUE TITLE
The Merged Data for Season 2022-23 Contains More Columns than Expected from the Header

### ISSUE THREAD

**Issue by ndrer** [vaastav/Fantasy-Premier-League#146]
If you load the merged_gw data for Season 2022-23 into Pandas, it returns error: "Error tokenizing data. C error: Expected 36 fields in line 7247, saw 41". There are some superfluous zeroes in the data for GW 15.

**Comment by vaastav** [comment]
Hmm looks like the FPL API added extra fields for players starting from GW15. That's why you are seeing the extra columns/superflous 0s. But looks like FPL will be providing xG, xA, xGI stats at some point in the future (perhaps after the world cup)

**Comment by vaastav** [comment]
I'll post a fix along with the GW12 fix in the coming week.

**Comment by vaastav** [comment]
This is fixed now.
