### ISSUE TITLE
GW1 - Missing Players

### ISSUE THREAD

**Issue by ralphgraham** [vaastav/Fantasy-Premier-League#15]
Hello, 

It looks like GW1 for 19/20 season is missing some players, gets to players beginning with 'M' and nothing after that, e.g. Pogba, Sterling etc.

Thanks!

Ralph

**Comment by vaastav** [comment]
If you are referring to this file : https://github.com/vaastav/Fantasy-Premier-League/blob/master/data/2019-20/gws/gw1.csv

I know the issue. I apologise for the inconvenience. It is an encoding issue that I should have sorted by end of today.

**Comment by vaastav** [comment]
It is fixed now! Cheers.

**Comment by thomas-woodruff** [comment]
Hello there,

Firstly, thanks for putting this repo together, it's really helpful.

I think there might be an encoding issue with some of the other gameweek csvs. For instance, when trying to `pd.read_csv(data/1617/gws/gw1.csv)`  I receive the following exception:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 17: unexpected end of data
```
