### ISSUE TITLE
Completed Passes from season 19/20 onwards

### ISSUE THREAD

**Issue by pedro-vr** [vaastav/Fantasy-Premier-League#152]
Hi vasstav, I started exploring the merged_gw data for all seasons and I could see that you have the completed_passes column for season 16/17, 17/18 and 18/19 but from season 19/20 I can't find it, do you have information about passes somewhere else?

Thanks in advance!

**Comment by vaastav** [comment]
I think FPL stopped providing that information from their API from 19/20 onwards.
