### ISSUE TITLE
GW36 data missing

### ISSUE THREAD

**Issue by ssenapaty** [vaastav/Fantasy-Premier-League#157]
It seems like GW36 data for the current season (2022-23) was never added.

**Comment by carlsen81** [comment]
Agreed. Same issue for me.

**Comment by vaastav** [comment]
ahh damn ok. Thanks for reporting. I'll try fixing it this week. The data is probably there in the individual player files but was probably never collected together to be in the gw36.csv file or in the merged_gws.csv file

**Comment by ssenapaty** [comment]
Yes, that matches what I observed. Thanks for all your work compiling and maintaining this data!

**Comment by OliverMitchell78** [comment]
Hi, I'm just adding to the comments here that I'd love to see GW36 added to complete the data set for FPL 2022/23!  Your data has given my mini league so many insights over the season and I'm grateful you've put in so much time and effort in pulling all of this together over the years - thank you!

**Comment by carlsen81** [comment]
Hi, just a heads up - the premier league fixtures for next season will be released tomorrow, might be a small time window left before this seasons data are erased for good. 
Hope you are well and we definitely appreciate this work. Thanks again.

**Comment by OliverMitchell78** [comment]
Hi, given that each player has GW36 data, surely we could just pull all that together to create a complete GW36 file? So even if the data online is erased, we’ll still be able to pull that together? I’m fairly new to this but hoping I’m right…

**Comment by vaastav** [comment]
@carlsen81 The data is already in the individual player files. Just hasn't been collected into 1 file. Even if FPL erases the data, there would be no issues.

**Comment by carlsen81** [comment]
alright alright, thats good to hear! Have a good summer.

**Comment by OliverMitchell78** [comment]
Not meaning to tread on any toes, but I just wanted to see if I could figure out a way of doing it - feel free to ignore me!

**Comment by vaastav** [comment]
Thanks for the effort @OliverMitchell78 but I had actually already taken care of it locally and just needed to push it which I have now.

**Comment by OliverMitchell78** [comment]
Thanks vaastav! Great work!

**Comment by ssenapaty** [comment]
Thank you!
