### ISSUE TITLE
Expected stats missing

### ISSUE THREAD

**Issue by nithincp** [vaastav/Fantasy-Premier-League#158]
Hi,

I can't find the expected stats for each individual player from their history (season/players/player_name/history.csv : Prior seasons history stats for that specific player.)
The expected stats like goals and assists seems to be having the value of 0.0 for the palyers.

Can you please let me know if this is an issue?

ThankYou

**Comment by vaastav** [comment]
FPL only added expected stats in the middle of the 2022-23 season so they probably don't have the expected stats from prior seasons.

**Comment by nithincp** [comment]
Thank you for the response.
