### ISSUE TITLE
Missing Players 2023/24

### ISSUE THREAD

**Issue by ThomasAllan** [vaastav/Fantasy-Premier-League#162]
As there was an update yesterday I was expecting to see some missing players resolved however coming a lot of players that aren't in the players initial load https://github.com/vaastav/Fantasy-Premier-League/tree/master/data/2023-24/players. 

Such as Pau Torres, Jurrien Timber, Justin Kluivert, Milos Kerkez

Not had this issue on previous seasons

**Comment by vaastav** [comment]
Fixed now.
