### ISSUE TITLE
data /master_team_list.csv issue

### ISSUE THREAD

**Issue by Fran3x** [vaastav/Fantasy-Premier-League#165]
It looks like teams we have listed for 2022-23 season in data/master_team_list.csv file include Burnley, Luton and Sheffield when I believe they should include Leicester, Leeds and Southampton instead. I also think this issue affected other files like cleaned_merged_seasons.csv and probably running global_merger.py again is required.

**Comment by vaastav** [comment]
Thanks! Fixed now.
