### ISSUE TITLE
Can you add data known before GW1 starts

### ISSUE THREAD

**Issue by jacksummers1995** [vaastav/Fantasy-Premier-League#166]
Can you add this for seasons past or give details on when I can find this information?

Many thanks :)

**Comment by vaastav** [comment]
Not sure if I understand your question. What data are you specifically looking for?

**Comment by jacksummers1995** [comment]
Thanks for your reply.

I mean any of the statatics and prices of players before GW1 has started. Any information that a player has available while picking their initial team
