### ISSUE TITLE
Accessing player team's picks?

### ISSUE THREAD

**Issue by elrobak** [vaastav/Fantasy-Premier-League#17]
As part of the team script would it be possible to add a pickup for the player picks for each gameweek?

The endpoint is https://fantasy.premierleague.com/api/entry/TEAMID/event/1/picks/ and I assume the number will increment up for each gameweek.

**Comment by vaastav** [comment]
Yes I am currently working on this.  Should be live by next week.

**Comment by elrobak** [comment]
Outstanding, thank you!

**Comment by vaastav** [comment]
let's keep the issue open until I add it in!
