### ISSUE TITLE
Using Data from This Repo in My Article

### ISSUE THREAD

**Issue by ms041223** [vaastav/Fantasy-Premier-League#179]
Hi,

I wanted to let you know that I am using the data from this repository in my latest article. Thank you so much for maintaining this repo, it has been incredibly useful!

Best regards,

Matt 

Ps here a link to the article if you are interested : https://medium.com/p/4ae31ff5d817

**Comment by vaastav** [comment]
I am glad you found the repo useful! I have added a link to your post in the README as a notable usage :)
