### ISSUE TITLE
Fixtures for previous seasons

### ISSUE THREAD

**Issue by djcarter85** [vaastav/Fantasy-Premier-League#18]
For 2019-20 there is a fixtures.csv file with all the matches in, but I notice that's not present for previous seasons (or at least I can't find it). Is that data available? I know they slightly changed the API this season.

What I'm particularly interested in is the Fixture Difficulty Ratings, as they could be useful in training an algorithm over last season's data.

**Comment by vaastav** [comment]
I am sorry but I don't have that data. I only started parsing the fixture difficulty ratings from this season.
Apologies.

**Comment by djcarter85** [comment]
That's fine, thanks for the swift reply!

Someone else may have done, in which case I'll raise a PR.

**Comment by vaastav** [comment]
That would be great!

**Comment by speeder1987** [comment]
I scraped the fixture data for the 2018/2019 season, although not for any of the earlier seasons. I haven't checked if the format and tags are the same. This was simply obtained by writing the old fixtures API directly into a CSV file.

[fixtures.zip](https://github.com/vaastav/Fantasy-Premier-League/files/3511161/fixtures.zip)

**Comment by vaastav** [comment]
@speeder1987  I have added it to the repo. And I have added your name in the acknowledgement section for providing it!

Thank you so much.
