### ISSUE TITLE
Team id's onto player rows

### ISSUE THREAD

**Issue by talhaki1771** [vaastav/Fantasy-Premier-League#180]
Hello, 

Thank you for your work in providing this data set.
I plan to use this data in SQL. As such, certain SQL queries may require the team name or team id of a player. Would it be possible for you to add the team id or team name for each player into the cleaned_players file?

Thank you.

**Comment by vaastav** [comment]
I think what you want is probably the players_raw.csv file as it is the superset of the cleaned_players file.
