### ISSUE TITLE
Update GW8 data for 2024-25

### ISSUE THREAD

**Issue by deepanks** [vaastav/Fantasy-Premier-League#189]
How many days before the gameweek, is the directory updated?

**Comment by ChaddersCheese** [comment]
Cutting it fine this week…

**Comment by deepanks** [comment]
Is there a write up on how to run the code to generate it myself. Thanks

**Comment by vaastav** [comment]
The repository is updated now.

If you want to run local updates then in the root directory of the repo execute the following: `python global_scraper.py`
