### ISSUE TITLE
Latest GW data

### ISSUE THREAD

**Issue by ferdizzz** [vaastav/Fantasy-Premier-League#191]
GW 10 data for this season hasn't been updated. Great work you doing here though!

**Comment by vaastav** [comment]
It's updated now.

**Comment by ferdizzz** [comment]
Why is it not automated tho??

**Comment by vaastav** [comment]
Fixtures being rescheduled broke the automation. 

I don't have the time to make an automation process that correctly handles rescheduled fixtures. At the end of the day, this is a free to use dataset and you can easily run the update locally if you need updated data on a quick turnaround.

**Comment by ferdizzz** [comment]
Yeahh fair enough...cheers!
