### ISSUE TITLE
Data for GW15 causing column inconsistencis

### ISSUE THREAD

**Issue by m-mukund** [vaastav/Fantasy-Premier-League#194]
The GW column for gameweek 15 seems to have been created in a new column altogether. Please check line 9299 in merged_gw.csv of 2024-25 data.

**Comment by rrichards7** [comment]
gw15 file has an additional column named "modified", which is messing with the merged gw csv since it expects 40 columns instead of 41

**Comment by vaastav** [comment]
It should be fixed now. Looks like the FPL backend API added a new column.
