### ISSUE TITLE
Merged data containing "FALSE" in opponent_team 12-08-2024 onwards

### ISSUE THREAD

**Issue by ossianhempel** [vaastav/Fantasy-Premier-League#195]
The column opponent_team in merged_gw contains FALSE instead of the opponent team id. Starts 12/08/2024 and continues for all rows. Is this a bug or something else?

**Comment by PeteJoh** [comment]
As I get this data after every game week, I noticed this starting on game week 15. All the data is there but the extra column moves the data over by one column.

**Comment by TheOX7** [comment]
@PeteJoh do you have any code to solve this issue?

**Comment by vaastav** [comment]
![image](https://github.com/user-attachments/assets/4c71bfe4-4a3d-4baa-bec2-e9e77127dddb)

The column seems to have correct data in the latest file

**Comment by ossianhempel** [comment]
Hmm okay, but its still wrong in merged_gw which i've been downloading. The opponents col has FALSE after the date i mentioned in my original post. Maybe it's shifted to the right.

**Comment by vaastav** [comment]
I just pushed GW17 data and everything seems correct in that. Might be caused by #194 which should be fixed now.

**Comment by ossianhempel** [comment]
Yes, now a boolean column "modified" has been added and opponent_team is correct again. Thanks @vaastav !
