### ISSUE TITLE
Players with the same name

### ISSUE THREAD

**Issue by antoniaelek** [vaastav/Fantasy-Premier-League#2]
Files are generated for players in folders by name, however, there are actually some players with the same name playing in the PL.

Both Leicester goalie and Cardiff midflielder are called Danny Ward and there is only csv generated for one of these two - the goalie. This is rather unfortunate for our midfielder Ward, who had quite a performance against Arsenal, bagging in a goal and 7 FPL points, yet his stats is not out there. 😃  

Maybe it would be better to also use player `id` or  `code` field in folder names. This way, instead of single `Danny Ward` folder, we would for example have both `Danny_Ward 95463` and `Danny_Ward 75826` and all their stats.

**Comment by vaastav** [comment]
Hmm that is definitely a problem. I think your solution makes sense.
It will take me a couple of days to get around to this.
Thank you for bringing this to my attention.

**Comment by vaastav** [comment]
Hi @antoniaelek , the feature you asked for has now been implemented.
I noticed that you are using my scripts to generated data for your website. I would really appreciate it if on your website you mention that you are obtaining the data using my scripts. 
I don't really care about the monetary gain and would just like a token of acknowledgement!
Thanks!

**Comment by antoniaelek** [comment]
Hi, yeah I mentioned it in blog post (https://aelek.me/fpl-stats-analysis/) already, gonna add it to the website, sure. I was jut redisining it last night so I haven't got around to adding it yet.

**Comment by vaastav** [comment]
That is great! Thanks so much :)
(Your website looks really good and so does your blog!)
Please let me know if you find any other kind of issues with the data or have some other fpl data needs!
If you are looking for collaborators for the website or any other football-related projects, I would love to help out :)

**Comment by vaastav** [comment]
Also, to return the favor, I added your website to this repo's Readme as one of the notable usages. Please let me know if you would like anything changed.

**Comment by vaastav** [comment]
No, I haven't published to medium but I have thought about it. Maybe one fine day if I stop being lazy.
Although I sometimes write for www.sportsgrape.com 
I did have one idea which I think would go very well with the website you seem to already be building. Customized charts/visualizations.  This would basically allow users to plot any metric they like and not just see pre-generated charts.  This idea shouldn't be that hard to implement and I think could be very useful for the fpl community (r/fantasypl especially).
There is also a very nice underlying research question which is how do we visualize all the key stats of 1 player in a single visualization which can then be easily compared with visualizations of other players. This idea I don't have a concrete answer to and would require research and some kind of novelty. Might even be submitable to a Visualization Research Conference (although may need to talk to my supervisor and one of the other profs in my department).
Lemme know if you find any of them interesting or have any other ideas that you think might be cool.

**Comment by antoniaelek** [comment]
Both of those sound great! 
I think, for visualization of all the key stats of 1 player, one woud probably end up creating something like those attributes graphs you get in games like PES or FIFA (like one below), only with FPL attributes, like goals scored, assists, clean sheets, saves, bonus points etc.
![image](https://user-images.githubusercontent.com/12903285/45925516-39392700-bf17-11e8-8667-72c2b181783c.png)

**Comment by vaastav** [comment]
That's what I initially thought too but I moved away from it as I didn't think it was scalable with the number of stats. Plus, the major question is what stats would even be included. Should it be the raw stats (points, goals, assists) or the underlying stats instead or maybe even a mix of both.
(PS Ewww why Hazard?)

**Comment by vaastav** [comment]
Yes, you are right that we should probably close this issue and move the discussion someplace else. Would you prefer email or something else?
Ahhh. I thought I had run into a fellow Arsenal supporter (I support Arsenal). Lucky you for being able to watch them live at the emirates.

**Comment by antoniaelek** [comment]
Yeah, mail is fine by me.
I just got rellay luck that time, yeah, not being a Gunner, but it was really amazing all the same, the stadium's just breathtaking and the game was great.

**Comment by vaastav** [comment]
Cool! I will send you an email to the address you have listed on your github profile. I am closing this issue!
Fun Fact : I saw the MLS all-stars game in 2016 in which Arsenal played live in the stadium. Guess who scored against Arsenal? Didier Drogba. (My seat was like 10 yards away from the goal)
