### ISSUE TITLE
Will you be updating fixtures.csv and teams.csv weekly?

### ISSUE THREAD

**Issue by cahn13** [vaastav/Fantasy-Premier-League#20]
I'm not a programmer but I find your data very helpful for collecting data on Excel and was wondering if you were going to update on a gameweekly basis

**Comment by vaastav** [comment]
Yea I think I will be updating the fixtures weekly. 
Don't think I will be updating the teams weekly.

I'm glad you find it useful!

**Comment by Tmcgeer** [comment]
The fixtures.csv and merged_gw.csv is extremely useful to us none developers. Would be amazing if you updated these. 

Think this project would get a lot more traffic and usage if you did update these regularly. I for one would use you as a source in my blog :)

**Comment by vaastav** [comment]
Those 2 files are updated after the end of every gameweek!
If you do end up using these in your blog, please send me a link and I will add it to the notable usages section
