### ISSUE TITLE
Basic data for upcoming GW?

### ISSUE THREAD

**Issue by pantisaz** [vaastav/Fantasy-Premier-League#21]
Hi, firstly thanks for doing this, this repo is amazing. 

I see that data for previous GWs is available but I was wondering how to obtain basic data for an upcoming GW? Stuff like:
Team data: Team names, Home/Away, Team strength, etc 
Player data: Prob of playing, Transfers in/out, etc

Thanks

**Comment by vaastav** [comment]
Hmm, I don't get the player data on a weekly basis but if you run the script everyday you can obtain that data.

The Team Data is in fixtures.csv
