### ISSUE TITLE
Missing columns in 2019-20 gameweek data

### ISSUE THREAD

**Issue by ssh24** [vaastav/Fantasy-Premier-League#22]
I have noticed the following columns are missing in the 2019-20 gw data, compared to the previous seasons:
```
['completed_passes', 'dribbles', 'attempted_passes', 'recoveries', 'open_play_crosses', 'clearances_blocks_interceptions', 'offside', 'errors_leading_to_goal_attempt', 'errors_leading_to_goal', 'penalties_conceded', 'big_chances_created', 'big_chances_missed', 'fouls', 'target_missed', 'key_passes']
```

Would it be possible to scrape those data and add them for the season?

**Comment by vaastav** [comment]
This data is no longer made available from the FPL folks via their API endpoints.

Unless I find the API endpoint that serves the data, I don't think it would be possible to get that data otherwise.

**Comment by antoniaelek** [comment]
No there isn't indeed, I was looking at another endpoint: https://fantasy.premierleague.com/api/bootstrap-static/
which I suppose does not work for you cause you're able to get only current gw's stats.
