### ISSUE TITLE
Gamweek csv encoding

### ISSUE THREAD

**Issue by thomas-woodruff** [vaastav/Fantasy-Premier-League#25]
Hello there,

Firstly, thanks for putting this repo together, it's really helpful.

I think there might be an encoding issue with some of the other gameweek csvs. For instance, when trying to `pd.read_csv('./data/1617/gws/gw1.csv')` I receive the following exception:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 17: unexpected end of data
```

Reposted from `https://github.com/vaastav/Fantasy-Premier-League/issues/15`

**Comment by thomas-woodruff** [comment]
Looks like the encoding is ISO-8859-1, so the following works:
`pd.read_csv('./data/1617/gws/gws/gw2.csv', encoding='ISO-8859-1')`

**Comment by vaastav** [comment]
No, the encoding is utf8.
Try using that instead of the ISO-8859-1 encoding.
