### ISSUE TITLE
Request: Player Fantasy Position

### ISSUE THREAD

**Issue by pastenague** [vaastav/Fantasy-Premier-League#26]
Hi Vaastav,

Would it be possible to add a column indicating each player's fantasy position (e.g. GK, DEF, MID, FWD) in the `players_raw.csv` file for each season? I'm doing some price analysis, and those files have the starting cost and price change over the season, but they don't contain each player's position, which I would like to include as a variable in my analysis.

Thank you!

**Comment by vaastav** [comment]
In players_raw.csv, element_type is the field that corresponds to the position. 1 = GK 2 = DEF 3 = MID 4 = FWD
