### ISSUE TITLE
GW 17 Data Error

### ISSUE THREAD

**Issue by pavelchek** [vaastav/Fantasy-Premier-League#35]
Hello,

In the most recent update, GW 17 data is a little off. In some rows of data for GW 17, GW 16 data is there. In some instances, GW16 data appears 3 weeks in a row (adding an extra GW).

Crystal Palace Players are where I noticed this error (look at Zaha and Tomkins). It appears for other teams as well. Could you please look into this?

Thank you,

Pablo

**Comment by vaastav** [comment]
Hmm weird.
Is this an issue in merged_gw.csv?

**Comment by pavelchek** [comment]
It's in issue in merged_gw.csv, and gw17.csv if you filter for Wilfred Zaha. I've seen other players as well (like Tomkins, Crystal Palace defender who got an assist in GW 17). Zaha scored a goal in GW 17 against Brighton but in gw17.csv he has 0 minutes and 0 goals, and in merged_gw.csv he has the same for GW17, but also GW 16 appears 3 times.

**Comment by vaastav** [comment]
Hmm ok. I think it should be fixed now. The automated data update probably didn't work.

**Comment by ravgeetdhillon** [comment]
This must have happened with Brighton and Crystal Palace players only. The thing is that the workflow last ran before their match. That's why the data from the them was unavailable.
@vaastav There is no problem with workflow.
