### ISSUE TITLE
GW27 Data Incorrect 

### ISSUE THREAD

**Issue by charliemoral** [vaastav/Fantasy-Premier-League#47]
Hi, same as last week, automated scripts have run before gameweek has finished so data is not complete and correct. 

Thanks

**Comment by ziggythedino** [comment]
Hi, on top of this it looks to me like when the gw26 data was reran some of the data was duplicated and the player scores were added twice - for example some Everton players have duplicate entries. Thanks :)

**Comment by vaastav** [comment]
Yea, the automation seems to have gone awry. I have fixed the data for now I think and have fixed the automation as well. There was an issue with the schedule that had been previously generated for the automation.
