### ISSUE TITLE
Something wrong with wk28 data

### ISSUE THREAD

**Issue by romer1979** [vaastav/Fantasy-Premier-League#50]
I have noticed something wrong about the data for week 28. for example, Doucoure from Watford has 14 points as it is shown in the data while he just got 6 points. Ahmed El Mohamady got -1 points but he did not play this week because he had a blank game week.

it looks like the script is gathering the wrong data for the wrong player.

**Comment by romer1979** [comment]
I'm here talking about gw28 file and noteverything

**Comment by vaastav** [comment]
The gw28 file looks correct to me
