### ISSUE TITLE
Please add player position and team to merged_gw file

### ISSUE THREAD

**Issue by FPLSecretWeapon** [vaastav/Fantasy-Premier-League#53]

**Comment by vaastav** [comment]
Hey, I will implement this for the new 2020-21 season!
Apologies for any incovenience.

**Comment by pascalchristian** [comment]
Hi, I second this as a player may move team in the winter window and currently there is no way of associating which team a player belong at a specific gameweek. While we are at it, can I request that player name and ID are added to the gw file as well? Right now we have a concatenated name_id which is hard to query.

**Comment by sanjaygopal** [comment]
Hi, 

Is there any table which has details on a player's position ? Thanks in advance. All the other data is really useful !
