### ISSUE TITLE
Units of now_cost

### ISSUE THREAD

**Issue by TOBEMAX007** [vaastav/Fantasy-Premier-League#55]
Just found this fabulous resource. Thanks so much. Just a query as to the units of the variable now_cost. For eg, Mo Salah currently has a cost 12.5 million (according to the official FFL site), but you record his "now_cost" as 126.  Is this something else, or is it a mistake and we need to divide by 10 to create the cost in millions of pounds?  Thanks again for the great work.

**Comment by vaastav** [comment]
FPL exports the cost as 125 which then needs to be divided by 10 to get the actual price.
