### ISSUE TITLE
Update the Gameweeks data

### ISSUE THREAD

**Issue by sauky** [vaastav/Fantasy-Premier-League#59]
Could someone please update the gw data in "/data/2019-20/gws/' from gw30 to gw38 since its blank and no longer available in fpl's api? Please.. i need the data to analyze players for 2020/21 squads :)

**Comment by aakashb95** [comment]
> gw30 to gw38 since its blank

It is blank because no matches were played on those dates due to COVID-19. So the data from GW30 - GW38 will be available in the same '/data/2019-20/gws/' folder  in GW31 - GW40 csv files.

**Comment by sauky** [comment]
Thank you!

**Comment by aakashb95** [comment]
Yes @sauky, it is available. https://fantasy.premierleague.com/api/bootstrap-static/ gives a json. Once you read it, check now_cost to find player prices.

**Comment by vaastav** [comment]
Closing this issue! Thank you @aakashb95
