### ISSUE TITLE
Player teams

### ISSUE THREAD

**Issue by area** [vaastav/Fantasy-Premier-League#6]
Is there a field anywhere that lets me know what team a player is playing for? Currently it looks like the best I can do is look at what team they don't have in their `opponent_team` column?

**Comment by vaastav** [comment]
In players_raw.csv file, the team is denoted by the 'team' column.
The numbering of teams is in alphabetical order according to FPL.
Eg: Arsenal -> 1 for 2018-19 season

**Comment by area** [comment]
Ah okay, in which case, my followup question is what happens when a player is moved during the January window?

**Comment by vaastav** [comment]
Yea the original team is just lost int that scenario.
Yea january transfers between the teams are not very well represented. The datais structured the same way as shown on the FPL website where, once the player is transferred, it is hard to figure out which was the previous team.
