### ISSUE TITLE
GH-Actions has overwritten 19-20 csv's with the 20/21 season data

### ISSUE THREAD

**Issue by ZeNoonan** [vaastav/Fantasy-Premier-League#60]
Looks like the GH-actions has overwritten the now_cost in the 19/20 cleaned_players.csv and 19/20 raw_players.csv with the 20/21 cost.  Better to have the 19/20 prices reflected in the 19/20 csv's rather than the 20/21 new player prices?

**Comment by vaastav** [comment]
Ahh that sucks.....I will revert the changes by tomorrow

**Comment by vaastav** [comment]
Should be fixed now.
