### ISSUE TITLE
Acknowledge data source

### ISSUE THREAD

**Issue by code247** [vaastav/Fantasy-Premier-League#61]
👍🏼 for this repo. I am rendering the player data in tabular form on my website here: [fantasynutmeg.com/history](http://www.fantasynutmeg.com/history)

**Comment by vaastav** [comment]
Thanks for letting me know!

**Comment by code247** [comment]
@vaastav Thank you for adding the reference. Although the link seems to be broken. You can change it to https://www.fantasynutmeg.com/history
