### ISSUE TITLE
2016-17 gw data id errors 

### ISSUE THREAD

**Issue by jackculpan** [vaastav/Fantasy-Premier-League#64]
Hey Vaastav and contributors - firstly, thank you for the great resource!

I have spotted an error within the gw data for the 2016-17 data. The ID column for a number of gws shows the player's code instead.

[example of replicated ID and element columns](https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/2016-17/gws/gw35.csv)

[example of different ID and element columns](https://raw.githubusercontent.com/vaastav/Fantasy-Premier-League/master/data/2016-17/gws/gw38.csv)

Thanks again,

**Comment by vaastav** [comment]
Could you tell me a player whose IDs are different ?

**Comment by jackculpan** [comment]
All of them from the 16-17 dataset, I believe.

https://github.com/vaastav/Fantasy-Premier-League/blob/master/data/2016-17/gws/gw1.csv
https://github.com/vaastav/Fantasy-Premier-League/blob/master/data/2016-17/gws/gw38.csv

Error is viewable within the gw38 dataset. The id is different to the element column for all players, which does not happen in gw1 column

**Comment by vaastav** [comment]
Ahh I see what you mean now. I believe the id column in those gw files has a different meaning than the id of the player (which is encoded by the element column). I am not fully certain what the id column meant back then but that column is no longer exported by FPL anymore and is deprecated. I would advise using the player_idlist for the player ids.

If I had to take a guess, it probably is the ID of the player for a match in a particular gw as the ID is monotonically increasing every gw for a player.

**Comment by jackculpan** [comment]
No worries - just thought it was worth mentioning! Caused me a few mindboggling errors until I worked out what was happening haha.

**Comment by vaastav** [comment]
Yup makes sense! Closing this issue now!
