### ISSUE TITLE
Some players missing in gwXX files e.g. emiliano martinez

### ISSUE THREAD

**Issue by sanskarjain** [vaastav/Fantasy-Premier-League#79]
Somewhere some join is causing some players to get dropped

**Comment by vaastav** [comment]
It could be due to the fact that some players have had blanks in certain gameweeks which would cause them to not appear in that gw.

**Comment by JohnP-1** [comment]
Yep, it is due to players not playing from games which were rescheduled. If you look at the data returned from the API there is no data for the players who didn't play for this reason.
