### ISSUE TITLE
Fixture codes

### ISSUE THREAD

**Issue by diogofernandesc** [vaastav/Fantasy-Premier-League#8]
Great work, any chance you have fixture codes per game week? 

As an example, in the current version of the API I can call https://fantasy.premierleague.com/drf/fixtures/ and each entry has a "code" field which I believe uniquely identifies that fixture, any chance you got this for the historical data?

Purpose would be to arrive at a standardised form for fixtures similar to what the current fixtures endpoint outputs. 

Thanks! 😄

**Comment by vaastav** [comment]
I don't have the historical data for this sorry :(
But I will get this data from next week regularly!! Thanks for bringing it to my notice.

**Comment by botbole** [comment]
is that data already in files as I didnt found it.
Do you know where I can find this historical data?
Thanks for this great project.

**Comment by vaastav** [comment]
No I haven't had time to parse that yet..... I probably won't have time to do that until the end of the season.
Sadly, I also don't have the historical data and I am unsure as to where to find it :(

**Comment by hungngo3** [comment]
I also think the fixture code is necessary as it helps us know what exact game the fixture code is. Thanks so much for your whole project.

**Comment by vaastav** [comment]
Add the fixture codes for this season. I will add it for the last season as well.
Closing this issue!
