### ISSUE TITLE
Issue with the merged_gw file

### ISSUE THREAD

**Issue by callistusndemo** [vaastav/Fantasy-Premier-League#86]
The `data/2020-21/gws/merged_gw.csv` file has some incorrect numbers. 

Below is an example looking at GW28's King of the Week, **Kelechi Iheanacho** 

![image](https://user-images.githubusercontent.com/29136312/111369702-c20b2680-866d-11eb-8feb-83c601a13fb4.png)

Game week 27 
![image](https://user-images.githubusercontent.com/29136312/111369907-f7177900-866d-11eb-9384-9cd0611e69ce.png)

Game week 28 
![image](https://user-images.githubusercontent.com/29136312/111370053-1dd5af80-866e-11eb-9be1-f37001a2996e.png)

Thanks for all the work on this project!

**Comment by vaastav** [comment]
So it seems like that the merged_gw file is pulling the wrong numbers? That seems weird. I will take a look and re-generate the merged_gw file from scratch

**Comment by callistusndemo** [comment]
Issue is fixed in the [latest](https://github.com/vaastav/Fantasy-Premier-League/commit/e894b25094ac4c9e214933d424e74400c5514df5) commit. Thank you!

**Comment by vaastav** [comment]
Alright perfect!
