### ISSUE TITLE
Do you know how team_code is assigned?

### ISSUE THREAD

**Issue by py9mrg** [vaastav/Fantasy-Premier-League#90]
Hello,

Thanks for this wonderful package.

I've noticed in players_raw.csv that there are two columns called `team` and `team_code`. As you already know, the former is the number assigned to that player's team, alphabetically, *for that season* - i.e. for 2020/21: Arsenal is 1, Aston Villa is 2, and so on. I want to go back over the previous season data and assign the right teams to the players.

This is a bit tricky when the number in `team` can change which team it is associated with every season - it's not impossible to do, but means scraping wikipedia for each season's list of teams. I think this could be a lot easier based on the fact that I've noticed that `team_code` is consistent across seasons - i.e. Arsenal is always 3, Aston Villa is always 7 and so on...

My problem is that I've no clue how this number gets assigned. It can't be based only on Premier League teams or Arsenal ought to be 1, and the numbers go as high as 91 (Bournemouth) or 110 (Stoke). Presumably it's from a list of clubs in England/Wales - but I can't work out what that list is or how the numbers were assigned to reverse engineer it. I was hoping you might have an idea?

**Comment by vaastav** [comment]
It seems like these are assigned behind the scenes by the fpl towers. I don;t think that data is public or at least I haven;t found it yet. Your best bet for now is to look at the teams.csv file to find the team_code for the teams from past 2 seasons and resolve as many teams as possible that way. The next step would be to manually map teams by looking at the teams of specific players in specific seasons.

**Comment by py9mrg** [comment]
Yeah no worries - I thought it might be an FPL behind the scenes thing. In the end I just scraped each season's Wikipedia page - they're all in the same format - e.g. https://en.wikipedia.org/wiki/2019%E2%80%9320_Premier_League.

If you wanted to do similar, *usually* the league table is the 5th table in the page (and you can use the following fixture table to get the team abbreviations, if you want to add them, too). Then some wrangling on the team names to match the FPL style - e.g. Tottenham Hotspurs => Spurs. Oh and one heads up - the team numbers are assigned alphabetically *except* Leeds and Leicester are switched so you have to flip them as well if they're both in the league. Probably not an issue for you as you've already sorted the 2020-21 season and they're not together before that. I would do a PR but I'm using R and my Python skills are pretty non-existent!
