### ISSUE TITLE
gw38.csv - ICT, Influence, threat and Creativity figures missing

### ISSUE THREAD

**Issue by Dran666** [vaastav/Fantasy-Premier-League#93]
Hi Vaastav,

gw38.csv has missing ICT, Influence, threat and Creativity figures.

For example Kevin De Bruyne has 0 for all these elements, yet had 55 BPS points, 2 bonus points and 13 overall points.

Is there any chance you can update the file to capture these figures, thanks

Dave

**Comment by vaastav** [comment]
This should be fixed in the latest commit of the data!
Apologies for the issue!
