### ISSUE TITLE
GW1 data(master/data/2021-22/gws/gw1.csv) seems to be incorrect

### ISSUE THREAD

**Issue by sajalgupta23** [vaastav/Fantasy-Premier-League#97]
GW1 data(master/data/2021-22/gws/gw1.csv) seems to be incorrect

**Comment by vaastav** [comment]
Can you give me an example of what is incorrect? It'll help me investigate.

**Comment by sajalgupta23** [comment]
Bunch of Stuff. Players teams seem to be wrong. For example - Cancelo is shown as having scored a hattrick(Bruno's stats)

**Comment by vaastav** [comment]
Alright, figured out the issue. Had not updated a stale link and it was using the team_ids and player_ids from last season. Fixed now. Thanks!
