### ISSUE TITLE
Data seems to be wrong

### ISSUE THREAD

**Issue by ssriram13** [vaastav/Fantasy-Premier-League#98]
1. Team names are off (e.g. Mahrez, Kevin De Bruyne in West Ham)
2. Points seems to be off 
3. Still shows old teams (Fulham etc.) and missing new teams (watford etc)

**Comment by ssriram13** [comment]
@vaastav - Your 'players' data seems to be correct but 'gw' data looks wrong. Might be a join/aggregation issue to create that.

**Comment by vaastav** [comment]
Alright, figured out the issue. Had not updated a stale link and it was using the team_ids and player_ids from last season. Fixed now. Thanks!
