### ISSUE TITLE
what some of the statistics mean

### ISSUE THREAD

**Issue by slkras** [vaastav/Fantasy-Premier-League#99]
Hi
Please explain what the following fields mean in statistics:
xP
bps
creativity
element
ict_index
influence
threat
transfers_balance
transfers_in
transfers_out
value
now_cost

**Comment by vaastav** [comment]
xP - Expected Points (from FPL website)
bps - Bonus Points
creativity - Creativity value that is part of the ICT value. Measures how creative the player was in the game.
element - ID of the player
ict_index - Rank of the player in the Influence Creativity Threat values
Influence - Influence value that is part of the ICT value. Measures the influence the player had on the game.
Threat - Threat value that is part of the ICT value. Measures how threatening the player was in the game.
transfers_in - Total number of teams that have transferred this player into the team this gw.
transfers_out - Total number of teams that have transferred this player out of the team this gw.
transfers_balance -  I think this is the net number of transfers.
now_cost - The price of the player
value - The price of the player.

**Comment by nasserqadri** [comment]
does xP refer to expected points for _upcoming_ week? for example, in the GW2 data, does the xP reflect expected points for GW3?
